#[cfg(windows)]
use std::{env, fs, path::PathBuf};

fn main() {
    #[cfg(windows)]
    {
        let resources = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"))
            .join("resources");
        fs::create_dir_all(&resources).expect("create Tauri resources directory");

        let destination = resources.join("crashpad_handler.exe");
        if !destination.is_file() {
            let handler = crashpad_handler_path();
            fs::copy(handler, &destination).expect("copy Crashpad handler into Tauri resources");
        }

        // The handler is generated by a dependency build script. Keep the
        // copied resource as the stable input for later Cargo invocations;
        // dependency caches do not preserve files copied to target/release.
        println!("cargo:rerun-if-changed={}", destination.display());
        println!("cargo:rerun-if-env-changed=DEP_SENTRY_NATIVE_CRASHPAD_HANDLER");
    }

    tauri_build::build();
}

#[cfg(windows)]
fn crashpad_handler_path() -> PathBuf {
    if let Some(handler) = env::var_os("DEP_SENTRY_NATIVE_CRASHPAD_HANDLER") {
        let handler = PathBuf::from(handler);
        if handler.is_file() {
            return handler;
        }
    }

    // Cargo only exposes build-script metadata to the immediate dependent.
    // sentry-contrib-native receives the handler path from its sys crate and
    // copies crashpad_handler.exe to Cargo's target/release directory, but it
    // cannot forward DEP_SENTRY_NATIVE_CRASHPAD_HANDLER to this crate.
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));
    let target_dir = out_dir
        .parent()
        .and_then(std::path::Path::parent)
        .and_then(std::path::Path::parent)
        .expect("find Cargo target directory");
    let handler = target_dir.join("crashpad_handler.exe");

    if handler.is_file() {
        return handler;
    }

    // sentry-contrib-native-sys keeps the generated handler below its own
    // target/release/build/<crate>/out directory. This is the path available
    // after a dependency cache restore, even when sentry-contrib-native's
    // target/release side-effect was intentionally pruned from the cache.
    if let Some(handler) = find_handler(&target_dir.join("build")) {
        return handler;
    }

    panic!(
        "sentry-contrib-native did not provide crashpad_handler.exe; searched {} and its build outputs",
        target_dir.display()
    );
}

#[cfg(windows)]
fn find_handler(root: &std::path::Path) -> Option<PathBuf> {
    for entry in fs::read_dir(root).ok()?.flatten() {
        let path = entry.path();
        if path.is_file()
            && path.file_name().and_then(|name| name.to_str()) == Some("crashpad_handler.exe")
        {
            return Some(path);
        }

        if path.is_dir() {
            if let Some(handler) = find_handler(&path) {
                return Some(handler);
            }
        }
    }

    None
}
